/**
 * Shape of the bundled demo fixtures (generated by `npm run fixtures:build`). OWNER: Architect.
 * catalog.json → FixtureCatalog, seed.json → FixtureSeed.
 */
import type { IsoDate, IsoDateTime, TitleDetail, TitleKey, WatchedWhere } from '@/lib/types';

/** A catalogue row: TitleDetail minus fields computed at runtime (isListed, detailStatus, fetchedAt). */
export type FixtureTitle = Omit<TitleDetail, 'isListed' | 'detailStatus' | 'fetchedAt'> & {
  /** Why this row exists, for curation edge cases (documentation only). */
  edgeCase?: string;
};

export interface FixtureCatalog {
  generatedAt: IsoDateTime;
  titles: FixtureTitle[];
}

export interface FixtureUser {
  id: string;
  handle: string;
  email: string;
  displayName: string;
  bio: string;
  avatarUrl: null;
  /** scrypt hash, see src/server/auth/password.ts. Password for all demo users: "stubbed-demo". */
  passwordHash: string;
  createdAt: IsoDateTime;
}

export interface FixtureStub {
  id: string;
  userId: string;
  titleKey: TitleKey;
  watchedOn: IsoDate;
  watchedWhere: WatchedWhere | null;
  note: string;
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

export interface FixtureReview {
  id: string;
  userId: string;
  titleKey: TitleKey;
  rating10: number;
  body: string;
  isSpoiler: boolean;
  stubId: string | null;
  imdbSharedAt: IsoDateTime | null;
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
  editedAt: IsoDateTime | null;
}

export interface FixtureWatchlistItem {
  userId: string;
  titleKey: TitleKey;
  addedAt: IsoDateTime;
}

export interface FixtureSeed {
  generatedAt: IsoDateTime;
  users: FixtureUser[];
  stubs: FixtureStub[];
  reviews: FixtureReview[];
  watchlist: FixtureWatchlistItem[];
}
